spring:
  application:
    name: registration-service

#  output:
#    ansi:
#      enabled: detect

  messages:
    basename: i18n/messages

  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/registration_service?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root123456


  #jpa
  #spring.jpa.properties.hibernate.jdbc.time_zone=UTC
  #This recipe shows you how to store date-time, and timestamps in UTC time zone in MySQL. For other RDBMSs (e.g. PostgreSQL), just remove "useLegacyDatetimeCode=false" and adapt the JDBC URL.
  jpa:
    open-in-view: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: none
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  h2:
    console:
      enabled: true
      path: /h2-console

  zipkin:
    base-url: http://192.168.10.117:9411/

#port
server:
  port: 8081



dubbo:
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.syphan.practice.registration.service.impl
  protocol:
    serialization: protostuff
    name: dubbo
    port: 20840
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
    simplified: true
  provider:
    timeout: 60000
    validation: true
    filter: tracing
  consumer:
    timeout: 60000
    check: false
    validation: true
    filter: tracing

#  Log Level — ERROR, WARN, INFO, DEBUG or TRACE.
logging:
  file:
    max-size: 100MB
    max-history: 15
  level:
    org:
      apache:
        dubbo: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
    com:
      jidian: debug
  path: logs

app:
  social:
    facebook:
      client-id: 574723326271010
      client-secret: 5aaa0aea0c1caf4e03a7c45d10dbb280
    google:
      client-ids:
        - 1037573039447-6pshsm1cf5lemrnpsbskmq87k1jnn7sr.apps.googleusercontent.com
      client-secret: 7zy3QCMNfeBDrinSb8CGTSll

debug: true
